### ISSUE TITLE
Using html-webpack-plugin >=2.24.1 shows warnings

### ISSUE THREAD

**Issue by js3692** [jamesjieye/html-webpack-exclude-assets-plugin#6] opened 2017-02-28 23:55 UTC
After https://github.com/jantimon/html-webpack-plugin/commit/4e29b022b89a6eeb7ba93ba92d0e955e83d2b997  and https://github.com/jantimon/html-webpack-plugin/commit/bac1cd4469ccc695464f1f98bf2accb3b48734fa were introduced, the plugin started to give errors for callbacks used without results.

Example:
<img width="678" alt="screen shot 2017-02-28 at 6 48 03 pm" src="https://cloud.githubusercontent.com/assets/14022304/23439977/5fe40994-fde7-11e6-9308-3ad9470c1027.png">

This is not an important issue, but the warnings started to clutter my output with multiple instances of `HtmlWebpackPlugin`. @jamesjieye Could you please look at the opened PR?

**Comment by jamesjieye** [comment] 2017-03-08 14:12
@js3692 sorry for the late response and thank your for the pull request. I have merged your pull request. And the cause of the Travis build failure is the upgrade of `loader-utils`, which used by `style-loader`, to 1.0.2. And `loader-utils` only supports node >=4.0.0 and therefore the build failed in node 0.12 environment.

**Closed as completed by jamesjieye** 2017-03-08 14:12 UTC

**Comment by js3692** [comment] 2017-03-09 14:41
Not a problem - thank you for the note!
